config/routes.rb
Ai::Application.routes.draw do

  resources :profiles

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users
  resources :users, :only => [:show, :update, :edit] do
    member do
      get :change_password
    end
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user && user.admin?
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard                  # allow access to dashboard
      if user.has_role? :superadmin
        can :manage, :all             # allow superadmins to do anything
      elsif user.has_role? :editor
        can :manage, [Role]  # allow managers to do anything to products and users
      elsif user.has_role? :sales
        can :update, Product, :hidden => false  # allow sales to only update visible products
      end
    end
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :first_name, :last_name
  has_paper_trail

  def full_name
    first_name + ' ' + last_name
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :user_roles
  has_many :users, :through => :user_roles
  has_paper_trail
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :create_profile
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :profile_attributes
  has_many :user_roles
  has_many :roles, :through => :user_roles
  has_one :profile
  delegate :first_name, :last_name, :full_name, :to => :profile
  accepts_nested_attributes_for :profile
  has_paper_trail


  def admin?
    has_role? :admin
  end


  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end

  def create_profile
    self.build_profile if self.profile.nil?
  end

  # edit profile without password
  def update_with_password(params={})
    if params[:current_password] then
      current_password = params.delete(:current_password)

      if params[:password].blank?
        params.delete(:password)
        params.delete(:password_confirmation) if params[:password_confirmation].blank?
      end

      result = if valid_password?(current_password)
                 update_attributes(params)
               else
                 self.attributes = params
                 self.valid?
                 self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
                 false
               end

      clean_up_passwords
      result
    else
      params.delete(:current_password)
      self.update_without_password(params)
    end
  end



end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
  has_paper_trail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from CanCan::AccessDenied do |exception|
      redirect_to root_url, :alert => exception.message
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check :only => [:index]
  def index

  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  load_and_authorize_resource
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  before_filter :authenticate_user!

  actions :show, :update
  custom_actions :resource => :change_password
  load_and_authorize_resource


  def update
    if params[:user][:password]
      if @user.update_with_password(params[:user])
        sign_in(@user, :bypass => true)
        redirect_to root_path, :notice => "Password updated!"
      else
        render :change_password
      end
    else
      super
    end
  end


  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def twitterized_type(type)
    case type
      when :alert
        "warning"
      when :error
        "error"
      when :notice
        "info"
      when :success
        "success"
      else
        type.to_s
      end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/index.html.erb
<div class="hero-unit">
  <h1>Hello Bootstrap</h1>
  <p>You are ready go..</p>

</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Myapp</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <style type="text/css">


          a {
            color: #0088cc;
            text-decoration: none;
          }
          a:hover {
            color: #005580;
            text-decoration: underline;
          }

      </style>
  </head>



  <body>
  <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <a class="brand" href="<%= root_path %>">MyApp</a>
            <div class="nav-collapse">
              <ul class="nav">
                <%=  render 'devise/menu/login_items' %>
                <%=  render 'devise/menu/registration_items' %>

              </ul>
              <%=  render 'devise/menu/logout' %>

            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>

      <div class="container">
        <%= render :partial => "shared/flash_messages", :locals => {:flash => flash} %>

        <%= yield %>

      </div> <!-- /container -->
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.first_name %></td>
    <td><%= profile.last_name %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @profile.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @profile.last_name %>
</p>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/shared/_flash_messages.html.erb
<div class="flash">
            <% flash.each do |type, message| -%>
                <div class="alert alert-<%= twitterized_type(type) %>">
                  <a class="close" data-dismiss="alert">×</a>
                  <p><%= message %></p>
                </div>
            <% end -%>
          </div>

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Sign up', new_user_registration_path)  %>
  </li>
<% end %>

app/views/users/change_password.html.erb
<%= simple_form_for @user, :as => @user, :html => {:method => :put, :class => 'form-horizontal'} do |f| %>
    <%= devise_error_messages! %>

    <%= f.input :current_password, :hint => "You must know you current password to change"  %>
    <%= f.input :password  %>
    <%= f.input :password_confirmation  %>



    <div class="form-actions">
        <%= f.button :submit, 'Update', :class => 'btn-primary' %>
        <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger" %>
    </div>

<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>User: <%= @user.username %></p>
<p>Email: <%= @user.email if @user.email %></p>